version: "3.8"

name: ampdresume-dev

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ampdresume
    ports:
      - "5432:5432"

volumes:
  postgres-data:
