export type VerticalSkillDefinition = {
  name: string;
  icon: string;
};

/**
 * Shared skill catalog for industry-vertical demo resumes. Names are unique and
 * reused across profiles via Skill / SkillForUser. Icons are Iconify identifiers.
 */
export const VERTICAL_SKILLS: VerticalSkillDefinition[] = [
  { name: "5G RAN Planning", icon: "mdi:antenna" },
  { name: "ARGUS", icon: "mdi:office-building" },
  { name: "AWS", icon: "mdi:aws" },
  { name: "Academic Advising", icon: "mdi:school" },
  { name: "Account Planning", icon: "mdi:account-tie" },
  { name: "Accreditation", icon: "mdi:certificate" },
  { name: "Actuarial Pricing", icon: "mdi:chart-bell-curve" },
  { name: "Policy Advocacy", icon: "mdi:bullhorn" },
  { name: "Airline Scheduling", icon: "mdi:calendar-clock" },
  { name: "Asset Management", icon: "mdi:domain" },
  { name: "Audit Analytics", icon: "mdi:chart-box" },
  { name: "AutoCAD", icon: "mdi:drawing" },
  { name: "Avionics", icon: "mdi:airplane-settings" },
  { name: "Brand Strategy", icon: "mdi:palette" },
  { name: "Budget Formulation", icon: "mdi:cash-multiple" },
  { name: "Building Codes", icon: "mdi:office-building-cog" },
  { name: "CMC Development", icon: "mdi:flask-round-bottom" },
  { name: "CRM", icon: "mdi:account-box-multiple" },
  { name: "Campaign Analytics", icon: "mdi:google-analytics" },
  { name: "Capital Markets", icon: "mdi:chart-line" },
  { name: "Care Coordination", icon: "mdi:account-heart" },
  { name: "Change Management", icon: "mdi:swap-horizontal" },
  { name: "Claims Management", icon: "mdi:file-document-check" },
  { name: "Clinical Development", icon: "mdi:microscope" },
  { name: "Clinical Operations", icon: "mdi:hospital-building" },
  { name: "Cloud Security", icon: "mdi:cloud-lock" },
  { name: "Commercial Lending", icon: "mdi:bank-transfer" },
  { name: "Compensation", icon: "mdi:cash" },
  { name: "Configuration Management", icon: "mdi:source-branch" },
  { name: "Construction Administration", icon: "mdi:hard-hat" },
  { name: "Construction Documents", icon: "mdi:file-cad" },
  { name: "Content Strategy", icon: "mdi:text-box-edit" },
  { name: "Contract Negotiation", icon: "mdi:handshake" },
  { name: "Corporate Governance", icon: "mdi:gavel" },
  { name: "Corporate Law", icon: "mdi:scale-balance" },
  { name: "Credit Analysis", icon: "mdi:credit-card-search" },
  { name: "Crew Resource Management", icon: "mdi:account-group" },
  { name: "Curriculum Design", icon: "mdi:book-education" },
  { name: "DCF Valuation", icon: "mdi:calculator-variant" },
  { name: "DO-178C", icon: "mdi:airplane-check" },
  { name: "Deal Execution", icon: "mdi:briefcase-check" },
  { name: "Demand Planning", icon: "mdi:chart-timeline-variant" },
  { name: "Design Development", icon: "mdi:vector-polyline" },
  { name: "Detection Engineering", icon: "mdi:radar" },
  { name: "Distributed Systems", icon: "mdi:server-network" },
  { name: "Donor Relations", icon: "mdi:hand-heart" },
  { name: "ERP", icon: "mdi:database-cog" },
  { name: "Electronic Health Records", icon: "mdi:file-document-outline" },
  { name: "Employee Relations", icon: "mdi:account-voice" },
  { name: "Enterprise Prospecting", icon: "mdi:target-account" },
  { name: "External Audit", icon: "mdi:clipboard-check" },
  { name: "FAA Compliance", icon: "mdi:airplane-alert" },
  { name: "FDA Regulatory Affairs", icon: "mdi:shield-check" },
  { name: "Fiber Deployment", icon: "mdi:ethernet-cable" },
  { name: "Financial Modeling", icon: "mdi:chart-areaspline" },
  { name: "Financial Reporting", icon: "mdi:file-chart" },
  { name: "Financial Underwriting", icon: "mdi:home-analytics" },
  { name: "Flight Operations", icon: "mdi:airplane" },
  { name: "Flight Test", icon: "mdi:airplane-search" },
  { name: "GCP", icon: "mdi:clipboard-text" },
  { name: "GRC", icon: "mdi:shield-account" },
  { name: "GAAP", icon: "mdi:book-open-variant" },
  { name: "Go", icon: "mdi:language-go" },
  { name: "Grant Management", icon: "mdi:file-sign" },
  { name: "Grant Writing", icon: "mdi:file-edit" },
  { name: "Grid Operations", icon: "mdi:transmission-tower" },
  { name: "HIPAA Compliance", icon: "mdi:shield-lock" },
  { name: "HRIS", icon: "mdi:card-account-details" },
  { name: "Hydraulics", icon: "mdi:water-pump" },
  { name: "Hypothesis-Driven Problem Solving", icon: "mdi:lightbulb-on" },
  { name: "IAM", icon: "mdi:key-chain" },
  { name: "Incident Response", icon: "mdi:alarm-light" },
  { name: "Industry Coverage", icon: "mdi:domain" },
  { name: "Institutional Research", icon: "mdi:chart-box-outline" },
  { name: "Internal Controls", icon: "mdi:lock-check" },
  { name: "Inventory Optimization", icon: "mdi:package-variant" },
  { name: "Issue Trees", icon: "mdi:file-tree" },
  { name: "Kubernetes", icon: "mdi:kubernetes" },
  { name: "LBO Analysis", icon: "mdi:chart-bar" },
  { name: "Lease Negotiation", icon: "mdi:file-sign" },
  { name: "Lean Manufacturing", icon: "mdi:factory" },
  { name: "Legal Research", icon: "mdi:book-search" },
  { name: "Legal Writing", icon: "mdi:fountain-pen" },
  { name: "Litigation Strategy", icon: "mdi:gavel" },
  { name: "Loan Structuring", icon: "mdi:bank" },
  { name: "Loss Modeling", icon: "mdi:chart-scatter-plot" },
  { name: "MEDDIC", icon: "mdi:clipboard-list" },
  { name: "MEP Coordination", icon: "mdi:pipe" },
  { name: "Maintenance Planning", icon: "mdi:wrench-clock" },
  { name: "Market Analysis", icon: "mdi:map-search" },
  { name: "Market Sizing", icon: "mdi:chart-donut" },
  { name: "Marketing Mix Modeling", icon: "mdi:chart-multiple" },
  { name: "Marketing Operations", icon: "mdi:cog-play" },
  { name: "Medical Affairs", icon: "mdi:stethoscope" },
  { name: "Model-Based Systems Engineering", icon: "mdi:sitemap" },
  { name: "Monitoring and Evaluation", icon: "mdi:clipboard-pulse" },
  { name: "NERC Compliance", icon: "mdi:transmission-tower-export" },
  { name: "Network Optimization", icon: "mdi:graph" },
  { name: "Network Planning", icon: "mdi:access-point-network" },
  { name: "Nonprofit Finance", icon: "mdi:cash-check" },
  { name: "Nursing Leadership", icon: "mdi:account-heart-outline" },
  { name: "OSS/BSS", icon: "mdi:server" },
  { name: "Observability", icon: "mdi:eye-check" },
  { name: "Opportunity Management", icon: "mdi:briefcase-plus" },
  { name: "Organizational Design", icon: "mdi:account-network" },
  { name: "PE Stamping", icon: "mdi:seal" },
  { name: "Patient Safety", icon: "mdi:hospital" },
  { name: "Penetration Testing", icon: "mdi:bug" },
  { name: "Pharmacovigilance", icon: "mdi:pill" },
  { name: "Pipeline Forecasting", icon: "mdi:chart-line-variant" },
  { name: "Pitch Books", icon: "mdi:presentation" },
  { name: "Policy Analysis", icon: "mdi:file-document-edit" },
  { name: "Policy Administration", icon: "mdi:file-cog" },
  { name: "Power Markets", icon: "mdi:lightning-bolt" },
  { name: "Process Safety", icon: "mdi:alert-octagon" },
  { name: "Procurement", icon: "mdi:cart-check" },
  { name: "Product Marketing", icon: "mdi:bullhorn-variant" },
  { name: "Production Planning", icon: "mdi:calendar-start" },
  { name: "Program Evaluation", icon: "mdi:clipboard-text-search" },
  { name: "Program Management", icon: "mdi:clipboard-flow" },
  { name: "Python", icon: "mdi:language-python" },
  { name: "Quality Improvement", icon: "mdi:trending-up" },
  { name: "Quality Management", icon: "mdi:quality-high" },
  { name: "React", icon: "mdi:react" },
  { name: "Regulatory Counseling", icon: "mdi:scale-balance" },
  { name: "Regulatory Writing", icon: "mdi:file-edit-outline" },
  { name: "Reinsurance", icon: "mdi:swap-horizontal-bold" },
  { name: "Relationship Management", icon: "mdi:account-supervisor" },
  { name: "Requirements Management", icon: "mdi:format-list-checks" },
  { name: "Reservoir Engineering", icon: "mdi:oil" },
  { name: "Revenue Cycle", icon: "mdi:cash-sync" },
  { name: "Revenue Management", icon: "mdi:ticket-percent" },
  { name: "Revit", icon: "mdi:home-city" },
  { name: "Risk Rating", icon: "mdi:speedometer" },
  { name: "S&OP", icon: "mdi:calendar-sync" },
  { name: "SCADA", icon: "mdi:monitor-dashboard" },
  { name: "SEO", icon: "mdi:search-web" },
  { name: "SIEM", icon: "mdi:security-network" },
  { name: "SOX Compliance", icon: "mdi:shield-check-outline" },
  { name: "SPC", icon: "mdi:chart-bell-curve-cumulative" },
  { name: "Safety Management Systems", icon: "mdi:shield-airplane" },
  { name: "Sales Engineering", icon: "mdi:toolbox" },
  { name: "Six Sigma", icon: "mdi:sigma" },
  { name: "Slide Storytelling", icon: "mdi:projector-screen" },
  { name: "Spectrum Management", icon: "mdi:radio-tower" },
  { name: "Stakeholder Management", icon: "mdi:account-multiple-check" },
  { name: "Structural Analysis", icon: "mdi:bridge" },
  { name: "Student Affairs", icon: "mdi:account-school" },
  { name: "Sustainable Design", icon: "mdi:leaf" },
  { name: "System Design", icon: "mdi:sitemap-outline" },
  { name: "Systems Engineering", icon: "mdi:cog-transfer" },
  { name: "TMS", icon: "mdi:truck-delivery" },
  { name: "TPM", icon: "mdi:wrench" },
  { name: "Talent Acquisition", icon: "mdi:account-search" },
  { name: "Tax Provision", icon: "mdi:receipt-text" },
  { name: "Technical Leadership", icon: "mdi:account-tie-hat" },
  { name: "Threat Hunting", icon: "mdi:target-account" },
  { name: "Treasury Management", icon: "mdi:safe" },
  { name: "Trial Operations", icon: "mdi:test-tube" },
  { name: "TypeScript", icon: "mdi:language-typescript" },
  { name: "Underwriting", icon: "mdi:file-check" },
  { name: "Urban Design", icon: "mdi:city-variant" },
  { name: "Value Selling", icon: "mdi:currency-usd" },
  { name: "Warehouse Management", icon: "mdi:warehouse" },
  { name: "Workforce Planning", icon: "mdi:account-clock" },
  { name: "Zero Trust", icon: "mdi:shield-lock-outline" },
  { name: "eDiscovery", icon: "mdi:database-search" },
];
