version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached
      - frontend-modules:/workspace/frontend/node_modules
      - backend-modules:/workspace/backend/node_modules
    command: sleep infinity
    network_mode: service:db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/mydatabase
      - NODE_ENV=development
    user: node

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

volumes:
  postgres-data:
  frontend-modules:
  backend-modules:
