export type LiterarySkillDefinition = {
  name: string;
  icon: string;
};

/**
 * Shared skill catalog for public-domain literary resumes. Names are unique and
 * reused across characters via Skill / SkillForUser. Icons are Iconify identifiers.
 * Only skills referenced by a character resume are listed here.
 */
export const LITERARY_SKILLS: LiterarySkillDefinition[] = [
  { name: "Accounting", icon: "mdi:calculator-variant" },
  { name: "Advocacy", icon: "mdi:podium" },
  { name: "Anatomy", icon: "mdi:human" },
  { name: "Archery", icon: "mdi:bow-arrow" },
  { name: "Assassination", icon: "mdi:target-account" },
  { name: "Banking", icon: "mdi:bank" },
  { name: "Biology", icon: "mdi:leaf" },
  { name: "Boxing", icon: "mdi:boxing-glove" },
  { name: "Cartography", icon: "mdi:map" },
  { name: "Charity", icon: "mdi:hand-heart" },
  { name: "Chemistry", icon: "mdi:flask" },
  { name: "Classical Scholarship", icon: "mdi:book-open-page-variant" },
  { name: "Command at Sea", icon: "mdi:ferry" },
  { name: "Court Intrigue", icon: "mdi:castle" },
  { name: "Criminal Strategy", icon: "mdi:chess-queen" },
  { name: "Cryptography", icon: "mdi:lock" },
  { name: "Cunning", icon: "mdi:owl" },
  { name: "Curiosity", icon: "mdi:magnify-plus" },
  { name: "Debate", icon: "mdi:forum" },
  { name: "Deduction", icon: "mdi:brain" },
  { name: "Diplomacy", icon: "mdi:handshake" },
  { name: "Disguise", icon: "mdi:incognito" },
  { name: "Dual Identity", icon: "mdi:account-switch" },
  { name: "Dueling", icon: "mdi:sword-cross" },
  { name: "Engineering", icon: "mdi:cog" },
  { name: "Experimental Biology", icon: "mdi:dna" },
  { name: "Farm Work", icon: "mdi:barn" },
  { name: "Fencing", icon: "mdi:fencing" },
  { name: "Field Medicine", icon: "mdi:medical-bag" },
  { name: "Forensic Chemistry", icon: "mdi:test-tube" },
  { name: "Forensic Medicine", icon: "mdi:fingerprint" },
  { name: "Forestry", icon: "mdi:forest" },
  { name: "Forgery", icon: "mdi:file-document-edit" },
  { name: "Galvanism", icon: "mdi:lightning-bolt" },
  { name: "Gentleman Burglary", icon: "mdi:hat-fedora" },
  { name: "Hospitality", icon: "mdi:home-heart" },
  { name: "Horsemanship", icon: "mdi:horse" },
  { name: "Infiltration", icon: "mdi:door" },
  { name: "Invisibility", icon: "mdi:eye-off" },
  { name: "Investigation", icon: "mdi:magnify" },
  { name: "Journalism", icon: "mdi:newspaper" },
  { name: "Languages", icon: "mdi:translate" },
  { name: "Law", icon: "mdi:gavel" },
  { name: "Leadership", icon: "mdi:account-group" },
  { name: "Letter Writing", icon: "mdi:email-edit" },
  { name: "Lockpicking", icon: "mdi:key-variant" },
  { name: "Logic", icon: "mdi:sitemap" },
  { name: "Logistics", icon: "mdi:truck" },
  { name: "Marksmanship", icon: "mdi:crosshairs-gps" },
  { name: "Mathematics", icon: "mdi:function-variant" },
  { name: "Mechanical Invention", icon: "mdi:robot" },
  { name: "Medical Practice", icon: "mdi:stethoscope" },
  { name: "Military Strategy", icon: "mdi:chess-king" },
  { name: "Moral Philosophy", icon: "mdi:scale-balance" },
  { name: "Music", icon: "mdi:violin" },
  { name: "Natural Philosophy", icon: "mdi:atom" },
  { name: "Navigation", icon: "mdi:compass" },
  { name: "Obsession", icon: "mdi:target" },
  { name: "Observation", icon: "mdi:eye" },
  { name: "Optics", icon: "mdi:glasses" },
  { name: "Outlaw Leadership", icon: "mdi:shield-account" },
  { name: "Paleontology", icon: "mdi:bone" },
  { name: "Pharmacology", icon: "mdi:pill" },
  { name: "Philosophy", icon: "mdi:head-lightbulb" },
  { name: "Physical Strength", icon: "mdi:arm-flex" },
  { name: "Piracy", icon: "mdi:skull-crossbones" },
  { name: "Poetry", icon: "mdi:feather" },
  { name: "Poisoncraft", icon: "mdi:bottle-tonic-skull" },
  { name: "Police Procedure", icon: "mdi:police-badge" },
  { name: "Prison Escape", icon: "mdi:jail" },
  { name: "Prison Reform", icon: "mdi:home-lock-open" },
  { name: "Private Investigation", icon: "mdi:briefcase-search" },
  { name: "Quest Leadership", icon: "mdi:shield-sword" },
  { name: "Resurrection Science", icon: "mdi:heart-flash" },
  { name: "Rhetoric", icon: "mdi:microphone" },
  { name: "Scientific Research", icon: "mdi:microscope" },
  { name: "Seamanship", icon: "mdi:anchor" },
  { name: "Social Engineering", icon: "mdi:account-voice" },
  { name: "Statecraft", icon: "mdi:crown" },
  { name: "Storytelling", icon: "mdi:book-open-variant" },
  { name: "Submarine Engineering", icon: "mdi:submarine" },
  { name: "Surgery", icon: "mdi:scissors-cutting" },
  { name: "Survival", icon: "mdi:campfire" },
  { name: "Swordsmanship", icon: "mdi:sword" },
  { name: "Tactical Leadership", icon: "mdi:strategy" },
  { name: "Time Travel", icon: "mdi:clock-fast" },
  { name: "Transformation", icon: "mdi:molecule" },
  { name: "Translation", icon: "mdi:book-alphabet" },
  { name: "Treasure Hunting", icon: "mdi:treasure-chest" },
  { name: "Weaving", icon: "mdi:loom" },
  { name: "Whaling", icon: "mdi:fish" },
  { name: "Wit", icon: "mdi:lightbulb-on" },
  { name: "Zoology", icon: "mdi:paw" },
];
