name: "Terraform Init and Plan"
description:
  "Initialize Terraform and run a plan to ensure the infrastructure will be created as expected"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Initialize Terraform
      working-directory: terraform
      shell: bash
      run: terraform init

    - name: Terraform Import Existing Buckets
      working-directory: terraform
      shell: bash
      run: |
        terraform import 'aws_s3_bucket.openresume_buckets["medialocal"]' medialocal.openresume.org
        terraform import 'aws_s3_bucket.openresume_buckets["mediatest"]' mediatest.openresume.org
        terraform import 'aws_s3_bucket.openresume_buckets["media"]' media.openresume.org

    - name: Validate Terraform
      working-directory: terraform
      shell: bash
      run: terraform validate

    - name: Plan Terraform
      working-directory: terraform
      shell: bash
      run: terraform plan

    - name: Apply Terraform
      working-directory: terraform
      shell: bash
      run: terraform apply -auto-approve
