name: "Terraform Init and Plan"
description:
  "Initialize Terraform and run a plan to ensure the infrastructure will be created as expected"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Initialize Terraform
      working-directory: terraform
      shell: bash
      run: terraform init

    - name: Validate Terraform
      working-directory: terraform
      shell: bash
      run: terraform validate

    - name: Plan Terraform
      working-directory: terraform
      shell: bash
      run: terraform plan
