name: "CD: App"

on:
  workflow_run:
    workflows: ["CI: App"]
    types:
      - completed
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_ENVIRONMENT: production

jobs:
  deploy-app:
    name: Deploy App
    if:
      github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch ==
      'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-dependencies

      - name: Run build
        run: npm run build
