name: "CD: App"

on:
  workflow_run:
    workflows: ["CI: App"]
    types:
      - completed
  workflow_dispatch:

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - id: set-env
        run: |
          if [[ "${{ github.event.workflow_run.head_branch }}" == "main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.workflow_run.head_branch }}" == "develop" ]]; then
            echo "environment=test" >> $GITHUB_OUTPUT
          else
            echo "environment=development" >> $GITHUB_OUTPUT
          fi

  deploy-app:
    needs: set-environment
    name: Deploy App
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    environment: ${{ needs.set-environment.outputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      NEXT_PUBLIC_ENVIRONMENT_NAME: ${{ needs.set-environment.outputs.environment }}

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-dependencies

      - name: Migrate database
        run: npm run prisma:migrate

      - name: Seed database
        run: npm run prisma:seed
