name: "CD: Infrastructure"

on:
  workflow_run:
    workflows: ["CI: Infrastructure"]
    types:
      - completed
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  infra-deploy:
    name: Deploy Infrastructure
    if:
      github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch ==
      'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/terraform-plan

      - name: Apply Terraform
        working-directory: terraform
        run: terraform apply -auto-approve
