name: "CD: Infrastructure"
description: "Deploy the infrastructure to AWS. Should only be run when Terraform changes are merged."

on:
  push:
    branches: [main]
    paths:
      - "**.tf"
      - "**.tfvars"
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  infra-deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/terraform-plan

      - name: Apply Terraform
        working-directory: terraform
        run: terraform apply -auto-approve
