name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  infra-deploy:
    if:
      github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch ==
      'main'
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/terraform-plan

      - name: Apply Terraform
        working-directory: terraform
        run: terraform apply -auto-approve

  code-deploy:
    name: Build Code
    runs-on: ubuntu-latest
    needs: [infra-deploy]
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-dependencies

      - name: Run build
        run: npm run build
