name: Continuous Integration, Frontend

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize]
    branches:
      - "main"
    paths:
      - "frontend/**.ts"
      - "frontend/**.tsx"
      - "frontend/**.scss"
      - "frontend/**.js"
      - "frontend/**.mjs"
      - "frontend/**.css"
      - "frontend/**.json"
  workflow_dispatch:

jobs:
  ci:
    name: Continuous Integration Tests, Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: install shared dependencies
        run: npm ci

      - name: install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: check formatting
        working-directory: ./frontend
        run: npm run prettier

      - name: check lint
        working-directory: ./frontend
        run: npm run lint

      - name: check types
        working-directory: ./frontend
        run: npm run types:check

      - name: run tests
        working-directory: ./frontend
        run: npm run test:coverage
