name: Smoke Test

on:
  workflow_dispatch:

env:
  # Used by local Postgres connection.
  DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/openresume
  # Used for sending emails for magic links.
  EMAIL_SERVER_HOST: email-smtp.us-west-2.amazonaws.com
  EMAIL_SERVER_PORT: 587
  EMAIL_SERVER_USER: ${{ secrets.EMAIL_SERVER_USER }}
  EMAIL_SERVER_PASSWORD: ${{ secrets.EMAIL_SERVER_PASSWORD }}
  EMAIL_FROM: OpenResume <mail@openresume.org>
  # Used for tracking, analytics, etc.
  NEXT_PUBLIC_ENVIRONMENT_NAME: test
  NEXT_PUBLIC_GRAPHQL_ENDPOINT: http://localhost:3000/api/graphql
  NEXT_PUBLIC_BASE_URL: http://localhost:3000
  # Used by NextAuth.js for authentication.
  NEXTAUTH_URL: http://localhost:3000
  NEXTAUTH_SECRET: this_is_obviously_not_a_secret
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  # Used by AWS SDK for S3 uploads.
  AWS_REGION: us-west-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET_NAME: medialocal.openresume.org
  # Used by Sentry for error tracking.
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-dependencies

      # Spin up a local Postgres instance.
      - name: Start Postgres
        run:
          docker run --name postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d
          postgres:16-alpine

      # Setup and seed local data.
      - name: Seed data
        run: npm run prisma:migrate && npm run prisma:seed

      - name: Setup Cypress
        run: |
          npm ci
          npm run cypress:install
        working-directory: cypress

      - name: Build Next.js app
        run: npm run build

      - name: Start Next.js app
        run: npm start &
        env:
          # Set environment variables for Next.js
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          # Add any other environment variables needed for your app

      - name: Wait for app to start
        run: npx wait-on http://localhost:3000 -t 60000

      - name: Run Cypress smoke tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: false
        env:
          # Cypress environment variables
          CYPRESS_BASE_URL: http://localhost:3000
          CYPRESS_TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          # AWS credentials for SES access
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # - name: Upload Cypress screenshots
      #   uses: actions/upload-artifact@v3
      #   if: failure()
      #   with:
      #     name: cypress-screenshots
      #     path: cypress/screenshots

      # - name: Upload Cypress videos
      #   uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: cypress-videos
      #     path: cypress/videos
